// <auto-generated />
namespace CustomTariff.Api2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_TariffClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_TariffClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201704201102083_Add_TariffClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
